"""Derive the implicit-GEMM 3x3 conv from the WMMA matmul, for both N tiles.

The conv is the matmul with exactly one thing substituted: the load that stages
a row of A becomes the im2col gather. Everything else -- W staging, the k-loop,
the LDS budget, the epilogue -- is the matmul's. Doing the substitution here,
by anchored edits that fail loudly if the source moves, means the 64-wide and
32-wide convs cannot drift from their matmuls or from each other.

  kernels/matmul_bias_f16_wmma_af16_cf16.loom  ->  kernels/conv3x3_f16_wmma.loom
"""
from __future__ import annotations

import argparse
import re
from pathlib import Path

KERNELS = Path(__file__).resolve().parent.parent / "kernels"

SOURCES = {
    # target stem: (source stem, source symbol, source namespace, target symbol, target namespace, N tile)
    "conv3x3_f16_wmma": ("matmul_bias_f16_wmma_af16_cf16", "dinov3_matmul_bias_f16_wmma_af16_cf16",
                         "dinov3.matmul_bias_f16_wmma_af16_cf16", "scrfd_conv3x3_f16_wmma",
                         "scrfd.conv3x3_f16_wmma", 64),
    # The 64x128 tile for the layers whose padded width is exactly 128 (tile_for in
    # tools/export_weights.py): same derivation, then widen_tile.
    "conv3x3_n128_f16_wmma": ("matmul_bias_f16_wmma_af16_cf16", "dinov3_matmul_bias_f16_wmma_af16_cf16",
                              "dinov3.matmul_bias_f16_wmma_af16_cf16", "scrfd_conv3x3_n128_f16_wmma",
                              "scrfd.conv3x3_n128_f16_wmma", 128),
}

HEADER = """// 3x3 convolution, pad 1, stride 1 or 2, as an implicit GEMM on the {tile}-wide-N WMMA
// staged-LDS matmul from dinov3-loom. Everything about that kernel is kept --
// the W staging, the k-loop, the LDS budget, the epilogue -- except the one load
// that stages a row of A: that load is now the im2col gather, so the [M][K]
// matrix never exists.
//
//   C[(b*Ho + yo)*Wo + xo, n] = bias[n] + sum_k A_gathered[row, k] * W[n, k]
//     with k = (dy*3 + dx)*Cin_pad + c, reading in[(b*H + yi)*W + xi, c] for
//     yi = yo*stride + dy - 1, xi = xo*stride + dx - 1, zero outside the image.
//
// A is NHWC f16 [B*H*W][Cin_stride]; W is [Cout_pad][K_pad] f16 in that k order
// (tools/export_weights.py); C is NHWC f16 [B*Ho*Wo][n_size]. f32 accumulate.
// Cin_pad and Cin_stride are multiples of 8: each lane gathers one row x
// vector<8xf16> per k-step, so a packet never straddles a tap.
//
// GENERATED by tools/gen_conv.py from {source}.loom; edit the generator.
//
"""

GATHER = """      // Implicit im2col: this row of A is output pixel (b, yo, xo) and this
      // column is tap (dy, dx) of channel c. Zero outside the image and beyond
      // 9*Cin_pad. Same address arithmetic as kernels/im2col_f16.loom, which
      // is tested exactly against NumPy.
      %in_k = index.cmp ult, %source_k, %k_real : index
      %gathers = scalar.andi %m_in_range, %in_k : i1
      %is_low = index.cmp eq, %half, %c0 : index
      %a_values = scf.if %gathers -> (vector<4xf16>) {
        %ys = scf.select %is_low, %h_ys0, %h_ys1 : index
        %xs = scf.select %is_low, %h_xs0, %h_xs1 : index
        %image_rows = scf.select %is_low, %h_rows0, %h_rows1 : index
        %tap = index.div %source_k, %cin_pad : index
        %c = index.rem %source_k, %cin_pad : index
        %dy = index.div %tap, %c3 : index
        %dx = index.rem %tap, %c3 : index
        // Clamp before subtracting: y0 = yo*stride + dy is never negative; the
        // tap is inside iff 1 <= y0 <= H, and only then is yi = y0 - 1 formed.
        %y0 = index.add %ys, %dy : index
        %x0 = index.add %xs, %dx : index
        %y_low = index.cmp uge, %y0, %c1 : index
        %y_high = index.cmp ule, %y0, %height : index
        %x_low = index.cmp uge, %x0, %c1 : index
        %x_high = index.cmp ule, %x0, %width : index
        %y_ok = scalar.andi %y_low, %y_high : i1
        %x_ok = scalar.andi %x_low, %x_high : i1
        %inside = scalar.andi %y_ok, %x_ok : i1
        %loaded = scf.if %inside -> (vector<4xf16>) {
          %yi0 = index.sub %y0, %c1 : index
          %xi0 = index.sub %x0, %c1 : index
          %yi = index.assume %yi0 [lt(%yi0, %height)] : index
          %xi = index.assume %xi0 [lt(%xi0, %width)] : index
          %row_y0 = index.add %image_rows, %yi : index
          %row_yw = index.mul %row_y0, %width : index
          %in_row0 = index.add %row_yw, %xi : index
          %in_row = index.assume %in_row0 [lt(%in_row0, %in_rows_total)] : index
          %c_col = index.assume %c [le(%c, %c_limit), mul(%c, 4)] : index
          %v = vector.load %a_view[%in_row, %c_col] : view<[%in_rows_total]x[%cin_stride]xf16> -> vector<4xf16>
          scf.yield %v : vector<4xf16>
        } else {
          scf.yield %zero_f16x4 : vector<4xf16>
        }
        scf.yield %loaded : vector<4xf16>
      } else {
        scf.yield %zero_f16x4 : vector<4xf16>
      }"""


PRELUDE = """  // Hoisted out of the k-loop: this workitem stages tile rows load_row and
  // load_row+32 -- two output pixels -- for every k. Their (image, y0, x0) never
  // change, so both are decomposed once here; per k only the tap and channel
  // of the column remain. Measured 1.05-1.10x on the real layers.
  %h_m0 = index.add %base_m, %load_row : index
  %h_m1 = index.add %base_m, %load_row_high : index
  %h_ok0 = index.cmp ult, %h_m0, %m_bounded : index
  %h_ok1 = index.cmp ult, %h_m1, %m_bounded : index
  %h_safe0 = scf.select %h_ok0, %h_m0, %c0 : index
  %h_safe1 = scf.select %h_ok1, %h_m1, %c0 : index
  %h_b0 = index.assume %h_safe0 [lt(%h_safe0, %m_bounded)] : index
  %h_b1 = index.assume %h_safe1 [lt(%h_safe1, %m_bounded)] : index
  %h_img0 = index.div %h_b0, %plane : index
  %h_img1 = index.div %h_b1, %plane : index
  %h_pix0 = index.rem %h_b0, %plane : index
  %h_pix1 = index.rem %h_b1, %plane : index
  %h_yo0 = index.div %h_pix0, %wo : index
  %h_yo1 = index.div %h_pix1, %wo : index
  %h_xo0 = index.rem %h_pix0, %wo : index
  %h_xo1 = index.rem %h_pix1, %wo : index
  %h_ys0 = index.mul %h_yo0, %stride : index
  %h_ys1 = index.mul %h_yo1, %stride : index
  %h_xs0 = index.mul %h_xo0, %stride : index
  %h_xs1 = index.mul %h_xo1, %stride : index
  %h_rows0 = index.mul %h_img0, %height : index
  %h_rows1 = index.mul %h_img1, %height : index

"""


def widen_gather(s: str, ns: str) -> str:
    """The derived kernel stages A as the matmul did: 256 lanes, two passes of 32
    rows x 8 packets of vector<4xf16>. Re-map to one pass of 64 rows x 4 packets
    of vector<8xf16>: half the loads and half the address arithmetic per k-step,
    one hoisted row per lane instead of two. Cin_pad and Cin_stride become
    multiples of 8 so a packet never straddles a tap. Measured 1.13-1.22x on the
    real layers (docs/notes.md, Lever 3)."""
    def sub(a: str, b: str) -> None:
        nonlocal s
        assert a in s, a[:70]
        s = s.replace(a, b, 1)
    for name in ("cin_pad", "cin_stride"):
        sub(f"config.decl @{ns}.{name} : %value: index where [range(%value, 4, 1024), mul(%value, 4)]",
            f"config.decl @{ns}.{name} : %value: index where [range(%value, 8, 1024), mul(%value, 8)]")
    sub("  %zero_f16x4 = vector.constant 0.0 : vector<4xf16>\n",
        "  %zero_f16x4 = vector.constant 0.0 : vector<4xf16>\n  %zero_f16x8 = vector.constant 0.0 : vector<8xf16>\n")
    sub("  %c_limit = index.sub %cin_pad, %c4 : index", "  %c_limit = index.sub %cin_pad, %c8 : index")
    sub("""  %load_packet = index.rem %workitem, %c8 : index
  %load_k = index.mul %load_packet, %c4 : index
  %load_row0 = index.div %workitem, %c8 : index
  %load_row = index.assume %load_row0 [range(%load_row0, 0, 31)] : index
  %load_row_high = index.add %load_row, %c32 : index
""", """  %load_packet = index.rem %workitem, %c4 : index
  %load_k = index.mul %load_packet, %c8 : index
  %load_row0 = index.div %workitem, %c4 : index
  %load_row = index.assume %load_row0 [range(%load_row0, 0, 63)] : index
""")
    s = "\n".join(l for l in s.split("\n") if not re.search(r"%h_[a-z]+1 = ", l))
    sub("""  // Hoisted out of the k-loop: this workitem stages tile rows load_row and
  // load_row+32 -- two output pixels -- for every k. Their (image, y0, x0) never
  // change, so both are decomposed once here; per k only the tap and channel
  // of the column remain. Measured 1.05-1.10x on the real layers.""",
        """  // Hoisted out of the k-loop: this workitem stages tile row load_row -- one
  // output pixel -- for every k, so its (image, y0, x0) is decomposed once here;
  // per k only the tap and channel of the column remain.""")
    sub("""    scf.for %half = [%c0 to %c2 step %c1] {
      %row_offset = index.mul %half, %c32 : index
      %row = index.add %load_row, %row_offset : index
""", """      %row = index.add %load_row, %c0 : index
""")
    sub("      %is_low = index.cmp eq, %half, %c0 : index\n", "")
    sub("        %ys = scf.select %is_low, %h_ys0, %h_ys1 : index\n        %xs = scf.select %is_low, %h_xs0, %h_xs1 : index\n        %image_rows = scf.select %is_low, %h_rows0, %h_rows1 : index\n",
        "        %ys = index.add %h_ys0, %c0 : index\n        %xs = index.add %h_xs0, %c0 : index\n        %image_rows = index.add %h_rows0, %c0 : index\n")
    sub("      vector.store %w_values, %w_stage_view[%row, %load_k] : vector<4xf16>, view<64x40xf16>\n    }\n",
        "      vector.store %w_values, %w_stage_view[%row, %load_k] : vector<4xf16>, view<64x40xf16>\n")
    a = s.index("      %in_k = index.cmp ult, %source_k, %k_real : index")
    b = s.index("    kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)")
    region = s[a:b].replace("vector<4xf16>", "vector<8xf16>").replace("%zero_f16x4", "%zero_f16x8").replace("mul(%c, 4)", "mul(%c, 8)")
    return s[:a] + region + s[b:]


def widen_tile(s: str, ns: str) -> str:
    """64x128 tile: eight waves with four accumulator fragments each, W staged 128
    rows wide in two passes, one LDS allocation of 15360 bytes with the result
    stage aliasing the dead A/W stages after the k-loop (4 workgroups/CU). 96
    VGPRs. Each row is gathered once for 128 columns instead of twice for 64:
    1.02-1.10x on the 80- and 88-channel layers, 0.82x on the 224-channel ones,
    which is why tile_for() gives it only n_size == 128 (docs/notes.md, Lever 4)."""
    def sub(a: str, b: str) -> None:
        nonlocal s
        assert a in s, a[:80]
        s = s.replace(a, b, 1)
    sub("  %n_tiles = index.div %n_size0, %c64 : index",
        "  %c128_cfg = index.constant 128 : index\n  %n_tiles = index.div %n_size0, %c128_cfg : index")
    sub(f"config.decl @{ns}.n_size : %value: index where [range(%value, 64, 8192), mul(%value, 64)]",
        f"config.decl @{ns}.n_size : %value: index where [range(%value, 128, 8192), mul(%value, 128)]")
    sub("  %n_size = index.assume %n_size0 [range(%n_size0, 64, 8192), mul(%n_size0, 64)] : index",
        "  %n_size = index.assume %n_size0 [range(%n_size0, 128, 8192), mul(%n_size0, 128)] : index")
    sub("  %c64 = index.constant 64 : index\n  %c256 = index.constant 256 : index\n  %c0_offset = index.constant 0 : offset\n",
        "  %c48 = index.constant 48 : index\n  %c64 = index.constant 64 : index\n  %c128 = index.constant 128 : index\n  %c256 = index.constant 256 : index\n  %c0_offset = index.constant 0 : offset\n")
    sub("  %a_stage_bytes = index.constant 5120 : offset\n  %w_stage_bytes = index.constant 5120 : offset\n  %result_stage_bytes = index.constant 8192 : offset\n",
        "  %lds_bytes = index.constant 15360 : offset\n  %w_stage_offset = index.constant 5120 : offset\n")
    sub("""  %a_stage = buffer.alloca<workgroup> align(16) %a_stage_bytes : buffer
  %w_stage = buffer.alloca<workgroup> align(16) %w_stage_bytes : buffer
  %result_stage = buffer.alloca<workgroup> align(16) %result_stage_bytes : buffer
  %a_stage_view = buffer.view %a_stage[%c0_offset] : buffer -> view<64x40xf16>
  %w_stage_view = buffer.view %w_stage[%c0_offset] : buffer -> view<64x40xf16>""",
        """  // One allocation: A at 0, W at 5120, and after the k-loop the eight waves'
  // 16x16 f32 result tiles over the dead stages.
  %lds = buffer.alloca<workgroup> align(16) %lds_bytes : buffer
  %a_stage_view = buffer.view %lds[%c0_offset] : buffer -> view<64x40xf16>
  %w_stage_view = buffer.view %lds[%w_stage_offset] : buffer -> view<128x40xf16>""")
    sub("  %w_fragment_view = buffer.view %w_stage[%c0_offset] : buffer -> view<32x64xf16, %w_fragment_layout>",
        "  %w_fragment_view = buffer.view %lds[%w_stage_offset] : buffer -> view<32x128xf16, %w_fragment_layout>")
    sub("  %result_view = buffer.view %result_stage[%wave_result_offset] : buffer -> view<16x16xf32>",
        "  %result_view = buffer.view %lds[%wave_result_offset] : buffer -> view<16x16xf32>")
    sub("  %wave_col = index.mul %wave_n, %c32 : index\n  %wave_col1 = index.add %wave_col, %c16 : index\n",
        "  %wave_col = index.mul %wave_n, %c64 : index\n  %wave_col1 = index.add %wave_col, %c16 : index\n  %wave_col2 = index.add %wave_col, %c32 : index\n  %wave_col3 = index.add %wave_col, %c48 : index\n")
    sub("  %base_n = index.mul %tile_n_id, %c64 : index", "  %base_n = index.mul %tile_n_id, %c128 : index")
    sub("  %acc_init1 = vector.fragment<init> %zero_f32x8 shape [%m, %n] : vector<8xf32>\n",
        "  %acc_init1 = vector.fragment<init> %zero_f32x8 shape [%m, %n] : vector<8xf32>\n  %acc_init2 = vector.fragment<init> %zero_f32x8 shape [%m, %n] : vector<8xf32>\n  %acc_init3 = vector.fragment<init> %zero_f32x8 shape [%m, %n] : vector<8xf32>\n")
    sub("  %acc0, %acc1 = scf.for %k_base = [%c0 to %k_size step %c32](%run0 = %acc_init0 : vector<8xf32>, %run1 = %acc_init1 : vector<8xf32>) -> (vector<8xf32>, vector<8xf32>) {",
        "  %acc0, %acc1, %acc2, %acc3 = scf.for %k_base = [%c0 to %k_size step %c32](%run0 = %acc_init0 : vector<8xf32>, %run1 = %acc_init1 : vector<8xf32>, %run2 = %acc_init2 : vector<8xf32>, %run3 = %acc_init3 : vector<8xf32>) -> (vector<8xf32>, vector<8xf32>, vector<8xf32>, vector<8xf32>) {")
    m = re.search(r"^( *)%source_n = index\.add %base_n, %row : index\n\1%w_values = vector\.load %w_view\[%source_n, %source_k\] : view<\[%n_size\]x\[%k_size\]xf16> -> vector<8xf16>\n\1vector\.store %w_values, %w_stage_view\[%row, %load_k\] : vector<8xf16>, view<64x40xf16>\n", s, re.M)
    assert m, "W staging block"
    ind = m.group(1)
    s = s[:m.start()] + f"""{ind}scf.for %w_half = [%c0 to %c2 step %c1] {{
{ind}  %w_row_offset = index.mul %w_half, %c64 : index
{ind}  %w_row = index.add %load_row, %w_row_offset : index
{ind}  %source_n = index.add %base_n, %w_row : index
{ind}  %w_values = vector.load %w_view[%source_n, %source_k] : view<[%n_size]x[%k_size]xf16> -> vector<8xf16>
{ind}  vector.store %w_values, %w_stage_view[%w_row, %load_k] : vector<8xf16>, view<128x40xf16>
{ind}}}
""" + s[m.end():]
    sub("    %next0, %next1 = scf.for %k_half = [%c0 to %c32 step %c16](%half0 = %run0 : vector<8xf32>, %half1 = %run1 : vector<8xf32>) -> (vector<8xf32>, vector<8xf32>) unroll {",
        "    %next0, %next1, %next2, %next3 = scf.for %k_half = [%c0 to %c32 step %c16](%half0 = %run0 : vector<8xf32>, %half1 = %run1 : vector<8xf32>, %half2 = %run2 : vector<8xf32>, %half3 = %run3 : vector<8xf32>) -> (vector<8xf32>, vector<8xf32>, vector<8xf32>, vector<8xf32>) unroll {")
    s = s.replace("view<32x64xf16, %w_fragment_layout>", "view<32x128xf16, %w_fragment_layout>")
    sub("      %rhs1 = vector.fragment.load<rhs> %w_fragment_view[%k_half, %wave_col1] shape [%k, %n] : view<32x128xf16, %w_fragment_layout> -> vector<16xf16>\n",
        "      %rhs1 = vector.fragment.load<rhs> %w_fragment_view[%k_half, %wave_col1] shape [%k, %n] : view<32x128xf16, %w_fragment_layout> -> vector<16xf16>\n"
        "      %rhs2 = vector.fragment.load<rhs> %w_fragment_view[%k_half, %wave_col2] shape [%k, %n] : view<32x128xf16, %w_fragment_layout> -> vector<16xf16>\n"
        "      %rhs3 = vector.fragment.load<rhs> %w_fragment_view[%k_half, %wave_col3] shape [%k, %n] : view<32x128xf16, %w_fragment_layout> -> vector<16xf16>\n")
    sub("      %out1 = vector.mma %lhs, %rhs1, %half1 : vector<16xf16>, vector<16xf16>, vector<8xf32>\n      scf.yield %out0, %out1 : vector<8xf32>, vector<8xf32>\n",
        "      %out1 = vector.mma %lhs, %rhs1, %half1 : vector<16xf16>, vector<16xf16>, vector<8xf32>\n      %out2 = vector.mma %lhs, %rhs2, %half2 : vector<16xf16>, vector<16xf16>, vector<8xf32>\n      %out3 = vector.mma %lhs, %rhs3, %half3 : vector<16xf16>, vector<16xf16>, vector<8xf32>\n      scf.yield %out0, %out1, %out2, %out3 : vector<8xf32>, vector<8xf32>, vector<8xf32>, vector<8xf32>\n")
    sub("    scf.yield %next0, %next1 : vector<8xf32>, vector<8xf32>\n", "    scf.yield %next0, %next1, %next2, %next3 : vector<8xf32>, vector<8xf32>, vector<8xf32>, vector<8xf32>\n")
    sub("  scf.for %fragment = [%c0 to %c2 step %c1] {\n    %is_second = index.cmp eq, %fragment, %c1 : index\n    %chosen = scf.select %is_second, %acc1, %acc0 : vector<8xf32>\n",
        "  scf.for %fragment = [%c0 to %c4 step %c1] {\n    %is1 = index.cmp eq, %fragment, %c1 : index\n    %is2 = index.cmp eq, %fragment, %c2 : index\n    %is3 = index.cmp eq, %fragment, %c3 : index\n    %pick01 = scf.select %is1, %acc1, %acc0 : vector<8xf32>\n    %pick012 = scf.select %is2, %acc2, %pick01 : vector<8xf32>\n    %chosen = scf.select %is3, %acc3, %pick012 : vector<8xf32>\n")
    return s


def prefetch(s: str, ns: str) -> str:
    """Register prefetch. The k-loop carries the next step's gathered A packet and
    W packet(s): each iteration stores the packets it was handed, barriers, issues
    the global loads for k+32 into registers, then runs the WMMA on the staged
    tile, so the load latency overlaps the multiply instead of stalling every
    step. Measured 1.05-1.25x on the real layers (docs/notes.md, Lever 8). The
    128-wide tile stages W in two passes; its loop is unrolled into two carried
    packets."""
    hdr = re.search(r"^  (%acc0[^=]*)= scf\.for %k_base = \[%c0 to %k_size step %c32\]\((.*?)\) -> \((.*?)\) \{\n", s, re.M)
    assert hdr, "k-loop header"
    results, iters, types = hdr.group(1).strip(), hdr.group(2), hdr.group(3)
    i = hdr.end()
    barrier = "    kernel.barrier<workgroup> scope(workgroup) ordering(acq_rel)\n"
    j = s.index(barrier, i)
    block = s[i:j]
    assert "%source_k = index.add %k_base, %load_k : index" in block
    prelude = ""
    w_loop = re.search(r"^ *scf\.for %w_half = \[%c0 to %c2 step %c1\] \{\n(?:.*\n)*? *\}\n", block, re.M)
    if w_loop:   # the 128-wide tile: two W rows per lane, explicit
        prelude = "  %w_row_hi = index.add %load_row, %c64 : index\n"
        block = block.replace(w_loop.group(0), """      %source_n = index.add %base_n, %load_row : index
      %source_n_hi = index.add %base_n, %w_row_hi : index
      %w_values = vector.load %w_view[%source_n, %source_k] : view<[%n_size]x[%k_size]xf16> -> vector<8xf16>
      %w_values_hi = vector.load %w_view[%source_n_hi, %source_k] : view<[%n_size]x[%k_size]xf16> -> vector<8xf16>
      vector.store %w_values, %w_stage_view[%load_row, %load_k] : vector<8xf16>, view<128x40xf16>
      vector.store %w_values_hi, %w_stage_view[%w_row_hi, %load_k] : vector<8xf16>, view<128x40xf16>
""")
    carried = ["%a_values", "%w_values"] + (["%w_values_hi"] if w_loop else [])
    stores = {}
    loads = block
    for name in carried:
        m = re.search(r"^ *vector\.store " + re.escape(name) + r",.*\n", loads, re.M)
        assert m, name
        stores[name] = m.group(0)
        loads = loads.replace(m.group(0), "")
    # the prefetch of the step after the last must not read past K
    for name, row in (("%w_values", "%source_n"), ("%w_values_hi", "%source_n_hi")):
        m = re.search(r"^( *)" + re.escape(name) + r" = vector\.load %w_view\[" + re.escape(row) + r", %source_k\] : view<\[%n_size\]x\[%k_size\]xf16> -> vector<8xf16>\n", loads, re.M)
        if not m:
            continue
        ind, tag = m.group(1), name[len("%w_values"):]
        loads = loads.replace(m.group(0), f"""{ind}%w_in_k{tag} = index.cmp ult, %source_k, %k_size : index
{ind}{name} = scf.if %w_in_k{tag} -> (vector<8xf16>) {{
{ind}  %w_k{tag} = index.assume %source_k [lt(%source_k, %k_size)] : index
{ind}  %w_loaded{tag} = vector.load %w_view[{row}, %w_k{tag}] : view<[%n_size]x[%k_size]xf16> -> vector<8xf16>
{ind}  scf.yield %w_loaded{tag} : vector<8xf16>
{ind}}} else {{
{ind}  scf.yield %zero_f16x8 : vector<8xf16>
{ind}}}
""")

    def instance(kvar: str, tag: str) -> tuple[str, list[str]]:
        t = loads.replace("%source_k = index.add %k_base, %load_k : index", f"%source_k = index.add {kvar}, %load_k : index")
        names = sorted(set(re.findall(r"^\s*(%[a-z_0-9]+) = ", t, re.M)), key=len, reverse=True)
        for n in names:
            t = re.sub(re.escape(n) + r"(?![a-z_0-9])", n + tag, t)
        return t, [c + tag for c in carried]

    pro, first = instance("%c0", "_first")
    body, nxt = instance("%k_next", "_next")
    cur = [c.replace("_values", "_cur") for c in carried]
    store_lines = "".join(stores[c].replace(c + ",", cur[k] + ",").replace("[%row, %load_k]", "[%load_row, %load_k]")
                          for k, c in enumerate(carried))
    iter_args = iters + "".join(f", {cur[k]} = {first[k]} : vector<8xf16>" for k in range(len(carried)))
    ret_types = types + ", vector<8xf16>" * len(carried)
    extra_results = "".join(f", %{c[1:]}_last" for c in carried)
    new = ("  // The first step's packets, gathered before the loop; every iteration then\n"
           "  // stores the packets it was handed and gathers the next step's while the\n"
           "  // WMMA runs on the staged tile.\n" + prelude + pro
           + f"  {results}{extra_results} = scf.for %k_base = [%c0 to %k_size step %c32]({iter_args}) -> ({ret_types}) {{\n"
           + store_lines + barrier + "    %k_next = index.add %k_base, %c32 : index\n" + body)
    k = s.index("    %next0, %next1", j)
    y = re.search(r"^    scf\.yield (%next0[^:]*) : ([^\n]*)\n", s[k:], re.M)
    assert y, "k-loop yield"
    e = k + y.start()
    return (s[:hdr.start()] + new + s[k:e]
            + f"    scf.yield {y.group(1)}, {', '.join(nxt)} : {y.group(2)}, {', '.join(['vector<8xf16>'] * len(carried))}\n"
            + s[e + len(y.group(0)):])


def derive(target: str) -> str:
    src_stem, src_sym, src_ns, sym, ns, tile = SOURCES[target]
    s = (KERNELS / f"{src_stem}.loom").read_text()
    s = s[s.index("amdgpu.target"):]                     # drop the matmul's own header
    s = s.replace(src_sym, sym).replace(src_ns, ns)
    import re
    target_name = re.search(r"amdgpu\.target<[^>]+> @(\S+)", s).group(1)
    s = s.replace(target_name, f"{sym}_gfx11")

    def sub(old: str, new: str) -> None:
        nonlocal s
        assert s.count(old) == 1, f"{src_stem}: anchor x{s.count(old)}:\n{old[:110]}"
        s = s.replace(old, new)

    sub(f"config.decl @{ns}.k_size : %value: index where [range(%value, 32, 8192), mul(%value, 32)]",
        f"""// Input height/width (NHWC, Cin_stride channels), stride, gather width and row
// stride. k_size is K_pad = 9*Cin_pad rounded to 32; the gather zero-fills the tail.
config.decl @{ns}.height : %value: index where [range(%value, 2, 4096), mul(%value, 2)]

config.decl @{ns}.width : %value: index where [range(%value, 2, 4096), mul(%value, 2)]

config.decl @{ns}.stride : %value: index where [range(%value, 1, 2)]

config.decl @{ns}.cin_pad : %value: index where [range(%value, 4, 1024), mul(%value, 4)]

// Physical channel stride of the input rows: the width its producer wrote,
// which is that conv's Cout_pad (64-aligned), or 4 for the stem's converted
// image. The gather reads only c < cin_pad inside each row, so the MMA work is
// 9*cin_pad, not 9*cin_stride -- for an 88-channel tensor stored 128 wide that
// is the difference between K=800 and K=1152.
config.decl @{ns}.cin_stride : %value: index where [range(%value, 4, 1024), mul(%value, 4)]

config.decl @{ns}.k_size : %value: index where [range(%value, 32, 16384), mul(%value, 32)]""")
    sub("%k_size = index.assume %k_size0 [range(%k_size0, 32, 8192), mul(%k_size0, 32)]",
        "%k_size = index.assume %k_size0 [range(%k_size0, 32, 16384), mul(%k_size0, 32)]")
    n_assume = [l for l in s.splitlines() if l.strip().startswith("%n_size = index.assume")][0]
    sub(n_assume + "\n", n_assume + f"""
  %height = config.get @{ns}.height : index
  %width = config.get @{ns}.width : index
  %stride = config.get @{ns}.stride : index
  %cin_pad = config.get @{ns}.cin_pad : index
  %cin_stride = config.get @{ns}.cin_stride : index
""")
    sub("  %a_view = buffer.view %a_global[%c0_offset] : buffer -> view<[%m_size]x[%k_size]xf16>",
        """  // A is the NHWC input [B*H*W][Cin_stride]; the [M][K] matrix is never formed.
  // M = B*Ho*Wo is a launch argument -- bounded here, never with `where`.
  %c3 = index.constant 3 : index
  %c9 = index.constant 9 : index
  %m_bounded = index.assume %m_size [range(%m_size, 1, 16777216)] : index
  %ho = index.div %height, %stride : index
  %wo = index.div %width, %stride : index
  %plane = index.mul %ho, %wo : index
  %images = index.div %m_bounded, %plane : index
  %in_rows_per_image = index.mul %height, %width : index
  %in_rows_total = index.mul %images, %in_rows_per_image : index
  %k_real = index.mul %cin_pad, %c9 : index
  %c_limit = index.sub %cin_pad, %c4 : index
  %a_view = buffer.view %a_global[%c0_offset] : buffer -> view<[%in_rows_total]x[%cin_stride]xf16>""")
    # the k-loop header is the same in both matmuls up to the accumulator list
    k_loop = [l for l in s.splitlines() if "scf.for %k_base = [%c0 to %k_size step %c32]" in l][0]
    sub(k_loop + "\n", PRELUDE + k_loop + "\n")
    sub("""      %a_values = scf.if %m_in_range -> (vector<4xf16>) {
        %bounded = index.assume %source_m [lt(%source_m, %m_size)] : index
        %narrow = vector.load %a_view[%bounded, %source_k] : view<[%m_size]x[%k_size]xf16> -> vector<4xf16>
        scf.yield %narrow : vector<4xf16>
      } else {
        scf.yield %zero_f16x4 : vector<4xf16>
      }""", GATHER)
    s = widen_gather(HEADER.format(tile=tile, source=src_stem) + s, ns)
    if tile == 128:
        s = widen_tile(s, ns)
    return prefetch(s, ns)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-dir", type=Path, default=KERNELS)
    args = parser.parse_args()
    for target in SOURCES:
        out = args.output_dir / f"{target}.loom"
        out.write_text(derive(target))
        print(f"wrote {out}")


if __name__ == "__main__":
    main()
