"""Generate the epilogue variants of the 3x3 conv from the one hand-written source.

The graph needs four epilogues on the 3x3 conv:

  plain     bias only                     FPN/PAFPN convs, the fused heads
  relu      relu(x + bias)                the stem, the first conv of each block, the head towers
  add       x + bias + residual           the two PAFPN bottom-up adds (no ReLU follows)
  relu_add  relu(x + bias + residual)     the second conv of every residual block

`residual` is an NHWC f16 tensor of the output's shape, added in the epilogue so
none of the graph's 16 Adds is ever a launch. Each variant is produced by literal
anchored edits, the way dinov3-loom's gen_f16_variants.py works: if the source
moves, the assert fails loudly rather than generating something subtly wrong.
"""
from __future__ import annotations

import argparse
from pathlib import Path

KERNELS = Path(__file__).resolve().parent.parent / "kernels"
SOURCE = "conv3x3_f16_wmma.loom"
SYMBOL = "scrfd_conv3x3_f16_wmma"
NAMESPACE = "scrfd.conv3x3_f16_wmma"

LAUNCH = "} launch(%m_size: index, %a: buffer, %w: buffer, %bias: buffer, %c: buffer) {"
LAUNCH_RESIDUAL = "} launch(%m_size: index, %a: buffer, %w: buffer, %bias: buffer, %c: buffer, %residual: buffer) {"

C_GLOBAL = "  %c_global = buffer.assume.memory_space<global> %c : buffer"
C_VIEW = "  %c_view = buffer.view %c_global[%c0_offset] : buffer -> view<[%m_size]x[%n_size]xf16>"
RESIDUAL_VIEW = """  %residual_global = buffer.assume.memory_space<global> %residual : buffer
  %residual_view = buffer.view %residual_global[%c0_offset] : buffer -> view<[%m_size]x[%n_size]xf16>"""

STORE = """        %narrow = vector.fptrunc %biased : vector<4xf32> to vector<4xf16>
        vector.store %narrow, %c_view[%bounded, %out_col] : vector<4xf16>, view<[%m_size]x[%n_size]xf16>"""

ADD = """        %prior_half = vector.load %residual_view[%bounded, %out_col] : view<[%m_size]x[%n_size]xf16> -> vector<4xf16>
        %prior = vector.extf %prior_half : vector<4xf16> to vector<4xf32>
        %summed = vector.addf %biased, %prior : vector<4xf32>
"""
RELU = """        %activated = vector.maxnumf %{src}, %zero_f32x4 : vector<4xf32>
"""

VARIANTS = {
    "relu": dict(residual=False, body=RELU.format(src="biased") + STORE.replace("%biased", "%activated")),
    "add": dict(residual=True, body=ADD + STORE.replace("%biased", "%summed")),
    "relu_add": dict(residual=True, body=ADD + RELU.format(src="summed") + STORE.replace("%biased", "%activated")),
}


def generate(variant: str, text: str) -> str:
    spec = VARIANTS[variant]
    for anchor in (LAUNCH, C_GLOBAL, C_VIEW, STORE, "%zero_f16x4 = vector.constant 0.0 : vector<4xf16>"):
        assert anchor in text, f"{SOURCE}: anchor moved\n{anchor[:90]}"
    out = text
    if spec["residual"]:
        out = out.replace(LAUNCH, LAUNCH_RESIDUAL)
        out = out.replace(C_VIEW, C_VIEW + "\n" + RESIDUAL_VIEW)
    out = out.replace("%zero_f16x4 = vector.constant 0.0 : vector<4xf16>",
                      "%zero_f16x4 = vector.constant 0.0 : vector<4xf16>\n"
                      "  %zero_f32x4 = vector.constant 0.0 : vector<4xf32>")
    out = out.replace(STORE, spec["body"].rstrip("\n"))
    out = out.replace(SYMBOL, f"{SYMBOL}_{variant}").replace(NAMESPACE, f"{NAMESPACE}_{variant}")
    return (f"// VARIANT `{variant}` of {SOURCE}: GENERATED by tools/gen_variants.py; edit the source.\n" + out)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-dir", type=Path, default=KERNELS,
                        help="write here instead of kernels/ (tests diff against it)")
    args = parser.parse_args()
    text = (KERNELS / SOURCE).read_text()
    for variant in VARIANTS:
        target = args.output_dir / f"conv3x3_f16_wmma_{variant}.loom"
        target.write_text(generate(variant, text))
        print(f"wrote {target}")


if __name__ == "__main__":
    main()
