"""Generate the epilogue variants of the 3x3 conv from the one hand-written source.

The graph needs four epilogues on the 3x3 conv:

  plain     bias only                     FPN/PAFPN convs, the fused heads
  relu      relu(x + bias)                the stem, the first conv of each block, the head towers
  add       x + bias + residual           the two PAFPN bottom-up adds (no ReLU follows)
  relu_add  relu(x + bias + residual)     the second conv of every residual block

`residual` is an NHWC f16 tensor of the output's shape, added in the epilogue so
none of the graph's 16 Adds is ever a launch. Each variant is produced by literal
anchored edits, the way dinov3-loom's gen_f16_variants.py works: if the source
moves, the assert fails loudly rather than generating something subtly wrong.
"""
from __future__ import annotations

import argparse
from pathlib import Path

KERNELS = Path(__file__).resolve().parent.parent / "kernels"
# (source file, export symbol, config namespace)
BASES = (("conv3x3_f16_wmma.loom", "scrfd_conv3x3_f16_wmma", "scrfd.conv3x3_f16_wmma"),
         ("conv3x3_n128_f16_wmma.loom", "scrfd_conv3x3_n128_f16_wmma", "scrfd.conv3x3_n128_f16_wmma"))
SOURCE, SYMBOL, NAMESPACE = BASES[0]

LAUNCH = "} launch(%m_size: index, %a: buffer, %w: buffer, %bias: buffer, %c: buffer) {"
LAUNCH_RESIDUAL = "} launch(%m_size: index, %a: buffer, %w: buffer, %bias: buffer, %c: buffer, %residual: buffer) {"

C_GLOBAL = "  %c_global = buffer.assume.memory_space<global> %c : buffer"
C_VIEW = "  %c_view = buffer.view %c_global[%c0_offset] : buffer -> view<[%m_size]x[%n_size]xf16>"
RESIDUAL_VIEW = """  %residual_global = buffer.assume.memory_space<global> %residual : buffer
  %residual_view = buffer.view %residual_global[%c0_offset] : buffer -> view<[%m_size]x[%n_size]xf16>"""

STORE = """        %narrow = vector.fptrunc %biased : vector<4xf32> to vector<4xf16>
        vector.store %narrow, %c_view[%bounded, %out_col] : vector<4xf16>, view<[%m_size]x[%n_size]xf16>"""

ADD = """        %prior_half = vector.load %residual_view[%bounded, %out_col] : view<[%m_size]x[%n_size]xf16> -> vector<4xf16>
        %prior = vector.extf %prior_half : vector<4xf16> to vector<4xf32>
        %summed = vector.addf %biased, %prior : vector<4xf32>
"""
RELU = """        %activated = vector.maxnumf %{src}, %zero_f32x4 : vector<4xf32>
"""

VARIANTS = {
    "relu": dict(residual=False, body=RELU.format(src="biased") + STORE.replace("%biased", "%activated")),
    "add": dict(residual=True, body=ADD + STORE.replace("%biased", "%summed")),
    "relu_add": dict(residual=True, body=ADD + RELU.format(src="summed") + STORE.replace("%biased", "%activated")),
}


def generate(variant: str, text: str, source: str = SOURCE, symbol: str = SYMBOL, namespace: str = NAMESPACE) -> str:
    spec = VARIANTS[variant]
    for anchor in (LAUNCH, C_GLOBAL, C_VIEW, STORE, "%zero_f16x4 = vector.constant 0.0 : vector<4xf16>"):
        assert anchor in text, f"{source}: anchor moved\n{anchor[:90]}"
    out = text
    if spec["residual"]:
        out = out.replace(LAUNCH, LAUNCH_RESIDUAL)
        out = out.replace(C_VIEW, C_VIEW + "\n" + RESIDUAL_VIEW)
    out = out.replace("%zero_f16x4 = vector.constant 0.0 : vector<4xf16>",
                      "%zero_f16x4 = vector.constant 0.0 : vector<4xf16>\n"
                      "  %zero_f32x4 = vector.constant 0.0 : vector<4xf32>")
    out = out.replace(STORE, spec["body"].rstrip("\n"))
    out = out.replace(symbol, f"{symbol}_{variant}").replace(namespace, f"{namespace}_{variant}")
    return (f"// VARIANT `{variant}` of {source}: GENERATED by tools/gen_variants.py; edit the source.\n" + out)


# --- the 1x1 lateral conv with the FPN add of the 2x-upsampled coarser level ----
#
# Two of the graph's Adds are  fine + Resize2x(coarse)  where `fine` is a 1x1 conv
# (our matmul) and `coarse` is the already-fused output one level down, half the
# height and width, same channel count. nearest/asymmetric/floor means the fine
# output at (b, y, x) adds coarse at (b, y/2, x/2), so the Resize never exists.
MM_SOURCE = "matmul_bias_f16_wmma_af16_cf16.loom"
MM_SYMBOL = "dinov3_matmul_bias_f16_wmma_af16_cf16"
MM_NAMESPACE = "dinov3.matmul_bias_f16_wmma_af16_cf16"
MM_LAUNCH = "} launch(%m_size: index, %a: buffer, %w: buffer, %bias: buffer, %c: buffer) {"
MM_LAUNCH_COARSE = "} launch(%m_size: index, %a: buffer, %w: buffer, %bias: buffer, %c: buffer, %coarse: buffer) {"
MM_N_CONFIG = f"config.decl @{MM_NAMESPACE}.n_size : %value: index where [range(%value, 64, 8192), mul(%value, 64)]"
MM_N_CONFIG_PLUS = MM_N_CONFIG + f"""

// Fine output height/width; the coarse tensor is half of each, same channels.
config.decl @{MM_NAMESPACE}.height : %value: index where [range(%value, 2, 4096), mul(%value, 2)]

config.decl @{MM_NAMESPACE}.width : %value: index where [range(%value, 2, 4096), mul(%value, 2)]"""
MM_C_VIEW = "  %c_view = buffer.view %c_global[%c0_offset] : buffer -> view<[%m_size]x[%n_size]xf16>"
MM_COARSE_VIEW = MM_C_VIEW + f"""
  %height = config.get @{MM_NAMESPACE}.height : index
  %width = config.get @{MM_NAMESPACE}.width : index
  %c2_r = index.constant 2 : index
  %plane = index.mul %height, %width : index
  %half_h = index.div %height, %c2_r : index
  %half_w = index.div %width, %c2_r : index
  %coarse_plane = index.mul %half_h, %half_w : index
  %m_bounded = index.assume %m_size [range(%m_size, 1, 16777216)] : index
  %images = index.div %m_bounded, %plane : index
  %coarse_rows = index.mul %images, %coarse_plane : index
  %coarse_global = buffer.assume.memory_space<global> %coarse : buffer
  %coarse_view = buffer.view %coarse_global[%c0_offset] : buffer -> view<[%coarse_rows]x[%n_size]xf16>"""
MM_STORE = STORE
MM_ADD_RESIZED = """        // fine row m = (b*H + y)*W + x  ->  coarse row (b*H/2 + y/2)*W/2 + x/2
        %image = index.div %bounded, %plane : index
        %pixel = index.rem %bounded, %plane : index
        %y = index.div %pixel, %width : index
        %x = index.rem %pixel, %width : index
        %yc = index.div %y, %c2_r : index
        %xc = index.div %x, %c2_r : index
        %img_rows = index.mul %image, %half_h : index
        %row_c0 = index.add %img_rows, %yc : index
        %row_cw = index.mul %row_c0, %half_w : index
        %coarse_row0 = index.add %row_cw, %xc : index
        %coarse_row = index.assume %coarse_row0 [lt(%coarse_row0, %coarse_rows)] : index
        %prior_half = vector.load %coarse_view[%coarse_row, %out_col] : view<[%coarse_rows]x[%n_size]xf16> -> vector<4xf16>
        %prior = vector.extf %prior_half : vector<4xf16> to vector<4xf32>
        %summed = vector.addf %biased, %prior : vector<4xf32>
""" + STORE.replace("%biased", "%summed")


def generate_add_resized(text: str) -> str:
    for anchor in (MM_LAUNCH, MM_N_CONFIG, MM_C_VIEW, MM_STORE):
        assert anchor in text, f"{MM_SOURCE}: anchor moved\n{anchor[:90]}"
    out = text.replace(MM_LAUNCH, MM_LAUNCH_COARSE).replace(MM_N_CONFIG, MM_N_CONFIG_PLUS)
    out = out.replace(MM_C_VIEW, MM_COARSE_VIEW).replace(MM_STORE, MM_ADD_RESIZED.rstrip("\n"))
    out = out.replace(MM_SYMBOL, "scrfd_matmul_add_resized_f16_wmma").replace(MM_NAMESPACE, "scrfd.matmul_add_resized_f16_wmma")
    return f"// VARIANT `add_resized` of {MM_SOURCE}: GENERATED by tools/gen_variants.py; edit the source.\n" + out


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-dir", type=Path, default=KERNELS,
                        help="write here instead of kernels/ (tests diff against it)")
    args = parser.parse_args()
    for source, symbol, namespace in BASES:
        text = (KERNELS / source).read_text()
        for variant in VARIANTS:
            target = args.output_dir / source.replace(".loom", f"_{variant}.loom")
            target.write_text(generate(variant, text, source, symbol, namespace))
            print(f"wrote {target}")
    target = args.output_dir / "matmul_add_resized_f16_wmma.loom"
    target.write_text(generate_add_resized((KERNELS / MM_SOURCE).read_text()))
    print(f"wrote {target}")


if __name__ == "__main__":
    main()
