"""Derive the implicit-GEMM 3x3 conv from the WMMA matmul, for both N tiles.

The conv is the matmul with exactly one thing substituted: the load that stages
a row of A becomes the im2col gather. Everything else -- W staging, the k-loop,
the LDS budget, the epilogue -- is the matmul's. Doing the substitution here,
by anchored edits that fail loudly if the source moves, means the 64-wide and
32-wide convs cannot drift from their matmuls or from each other.

  kernels/matmul_bias_f16_wmma_af16_cf16.loom  ->  kernels/conv3x3_f16_wmma.loom
"""
from __future__ import annotations

import argparse
from pathlib import Path

KERNELS = Path(__file__).resolve().parent.parent / "kernels"

SOURCES = {
    # target stem: (source stem, source symbol, source namespace, target symbol, target namespace, N tile)
    "conv3x3_f16_wmma": ("matmul_bias_f16_wmma_af16_cf16", "dinov3_matmul_bias_f16_wmma_af16_cf16",
                         "dinov3.matmul_bias_f16_wmma_af16_cf16", "scrfd_conv3x3_f16_wmma",
                         "scrfd.conv3x3_f16_wmma", 64),
}

HEADER = """// 3x3 convolution, pad 1, stride 1 or 2, as an implicit GEMM on the {tile}-wide-N WMMA
// staged-LDS matmul from dinov3-loom. Everything about that kernel is kept --
// the W staging, the k-loop, the LDS budget, the epilogue -- except the one load
// that stages a row of A: that load is now the im2col gather, so the [M][K]
// matrix never exists.
//
//   C[(b*Ho + yo)*Wo + xo, n] = bias[n] + sum_k A_gathered[row, k] * W[n, k]
//     with k = (dy*3 + dx)*Cin_pad + c, reading in[(b*H + yi)*W + xi, c] for
//     yi = yo*stride + dy - 1, xi = xo*stride + dx - 1, zero outside the image.
//
// A is NHWC f16 [B*H*W][Cin_stride]; W is [Cout_pad][K_pad] f16 in that k order
// (tools/export_weights.py); C is NHWC f16 [B*Ho*Wo][n_size]. f32 accumulate.
//
// GENERATED by tools/gen_conv.py from {source}.loom; edit the generator.
//
"""

GATHER = """      // Implicit im2col: this row of A is output pixel (b, yo, xo) and this
      // column is tap (dy, dx) of channel c. Zero outside the image and beyond
      // 9*Cin_pad. Same address arithmetic as kernels/im2col_f16.loom, which
      // is tested exactly against NumPy.
      %in_k = index.cmp ult, %source_k, %k_real : index
      %gathers = scalar.andi %m_in_range, %in_k : i1
      %is_low = index.cmp eq, %half, %c0 : index
      %a_values = scf.if %gathers -> (vector<4xf16>) {
        %ys = scf.select %is_low, %h_ys0, %h_ys1 : index
        %xs = scf.select %is_low, %h_xs0, %h_xs1 : index
        %image_rows = scf.select %is_low, %h_rows0, %h_rows1 : index
        %tap = index.div %source_k, %cin_pad : index
        %c = index.rem %source_k, %cin_pad : index
        %dy = index.div %tap, %c3 : index
        %dx = index.rem %tap, %c3 : index
        // Clamp before subtracting: y0 = yo*stride + dy is never negative; the
        // tap is inside iff 1 <= y0 <= H, and only then is yi = y0 - 1 formed.
        %y0 = index.add %ys, %dy : index
        %x0 = index.add %xs, %dx : index
        %y_low = index.cmp uge, %y0, %c1 : index
        %y_high = index.cmp ule, %y0, %height : index
        %x_low = index.cmp uge, %x0, %c1 : index
        %x_high = index.cmp ule, %x0, %width : index
        %y_ok = scalar.andi %y_low, %y_high : i1
        %x_ok = scalar.andi %x_low, %x_high : i1
        %inside = scalar.andi %y_ok, %x_ok : i1
        %loaded = scf.if %inside -> (vector<4xf16>) {
          %yi0 = index.sub %y0, %c1 : index
          %xi0 = index.sub %x0, %c1 : index
          %yi = index.assume %yi0 [lt(%yi0, %height)] : index
          %xi = index.assume %xi0 [lt(%xi0, %width)] : index
          %row_y0 = index.add %image_rows, %yi : index
          %row_yw = index.mul %row_y0, %width : index
          %in_row0 = index.add %row_yw, %xi : index
          %in_row = index.assume %in_row0 [lt(%in_row0, %in_rows_total)] : index
          %c_col = index.assume %c [le(%c, %c_limit), mul(%c, 4)] : index
          %v = vector.load %a_view[%in_row, %c_col] : view<[%in_rows_total]x[%cin_stride]xf16> -> vector<4xf16>
          scf.yield %v : vector<4xf16>
        } else {
          scf.yield %zero_f16x4 : vector<4xf16>
        }
        scf.yield %loaded : vector<4xf16>
      } else {
        scf.yield %zero_f16x4 : vector<4xf16>
      }"""


PRELUDE = """  // Hoisted out of the k-loop: this workitem stages tile rows load_row and
  // load_row+32 -- two output pixels -- for every k. Their (image, y0, x0) never
  // change, so both are decomposed once here; per k only the tap and channel
  // of the column remain. Measured 1.05-1.10x on the real layers.
  %h_m0 = index.add %base_m, %load_row : index
  %h_m1 = index.add %base_m, %load_row_high : index
  %h_ok0 = index.cmp ult, %h_m0, %m_bounded : index
  %h_ok1 = index.cmp ult, %h_m1, %m_bounded : index
  %h_safe0 = scf.select %h_ok0, %h_m0, %c0 : index
  %h_safe1 = scf.select %h_ok1, %h_m1, %c0 : index
  %h_b0 = index.assume %h_safe0 [lt(%h_safe0, %m_bounded)] : index
  %h_b1 = index.assume %h_safe1 [lt(%h_safe1, %m_bounded)] : index
  %h_img0 = index.div %h_b0, %plane : index
  %h_img1 = index.div %h_b1, %plane : index
  %h_pix0 = index.rem %h_b0, %plane : index
  %h_pix1 = index.rem %h_b1, %plane : index
  %h_yo0 = index.div %h_pix0, %wo : index
  %h_yo1 = index.div %h_pix1, %wo : index
  %h_xo0 = index.rem %h_pix0, %wo : index
  %h_xo1 = index.rem %h_pix1, %wo : index
  %h_ys0 = index.mul %h_yo0, %stride : index
  %h_ys1 = index.mul %h_yo1, %stride : index
  %h_xs0 = index.mul %h_xo0, %stride : index
  %h_xs1 = index.mul %h_xo1, %stride : index
  %h_rows0 = index.mul %h_img0, %height : index
  %h_rows1 = index.mul %h_img1, %height : index

"""


def derive(target: str) -> str:
    src_stem, src_sym, src_ns, sym, ns, tile = SOURCES[target]
    s = (KERNELS / f"{src_stem}.loom").read_text()
    s = s[s.index("amdgpu.target"):]                     # drop the matmul's own header
    s = s.replace(src_sym, sym).replace(src_ns, ns)
    import re
    target_name = re.search(r"amdgpu\.target<[^>]+> @(\S+)", s).group(1)
    s = s.replace(target_name, f"{sym}_gfx11")

    def sub(old: str, new: str) -> None:
        nonlocal s
        assert s.count(old) == 1, f"{src_stem}: anchor x{s.count(old)}:\n{old[:110]}"
        s = s.replace(old, new)

    sub(f"config.decl @{ns}.k_size : %value: index where [range(%value, 32, 8192), mul(%value, 32)]",
        f"""// Input height/width (NHWC, Cin_stride channels), stride, gather width and row
// stride. k_size is K_pad = 9*Cin_pad rounded to 32; the gather zero-fills the tail.
config.decl @{ns}.height : %value: index where [range(%value, 2, 4096), mul(%value, 2)]

config.decl @{ns}.width : %value: index where [range(%value, 2, 4096), mul(%value, 2)]

config.decl @{ns}.stride : %value: index where [range(%value, 1, 2)]

config.decl @{ns}.cin_pad : %value: index where [range(%value, 4, 1024), mul(%value, 4)]

// Physical channel stride of the input rows: the width its producer wrote,
// which is that conv's Cout_pad (64-aligned), or 4 for the stem's converted
// image. The gather reads only c < cin_pad inside each row, so the MMA work is
// 9*cin_pad, not 9*cin_stride -- for an 88-channel tensor stored 128 wide that
// is the difference between K=800 and K=1152.
config.decl @{ns}.cin_stride : %value: index where [range(%value, 4, 1024), mul(%value, 4)]

config.decl @{ns}.k_size : %value: index where [range(%value, 32, 16384), mul(%value, 32)]""")
    n_assume = [l for l in s.splitlines() if l.strip().startswith("%n_size = index.assume")][0]
    sub(n_assume + "\n", n_assume + f"""
  %height = config.get @{ns}.height : index
  %width = config.get @{ns}.width : index
  %stride = config.get @{ns}.stride : index
  %cin_pad = config.get @{ns}.cin_pad : index
  %cin_stride = config.get @{ns}.cin_stride : index
""")
    sub("  %a_view = buffer.view %a_global[%c0_offset] : buffer -> view<[%m_size]x[%k_size]xf16>",
        """  // A is the NHWC input [B*H*W][Cin_stride]; the [M][K] matrix is never formed.
  // M = B*Ho*Wo is a launch argument -- bounded here, never with `where`.
  %c3 = index.constant 3 : index
  %c9 = index.constant 9 : index
  %m_bounded = index.assume %m_size [range(%m_size, 1, 16777216)] : index
  %ho = index.div %height, %stride : index
  %wo = index.div %width, %stride : index
  %plane = index.mul %ho, %wo : index
  %images = index.div %m_bounded, %plane : index
  %in_rows_per_image = index.mul %height, %width : index
  %in_rows_total = index.mul %images, %in_rows_per_image : index
  %k_real = index.mul %cin_pad, %c9 : index
  %c_limit = index.sub %cin_pad, %c4 : index
  %a_view = buffer.view %a_global[%c0_offset] : buffer -> view<[%in_rows_total]x[%cin_stride]xf16>""")
    # the k-loop header is the same in both matmuls up to the accumulator list
    k_loop = [l for l in s.splitlines() if "scf.for %k_base = [%c0 to %k_size step %c32]" in l][0]
    sub(k_loop + "\n", PRELUDE + k_loop + "\n")
    sub("""      %a_values = scf.if %m_in_range -> (vector<4xf16>) {
        %bounded = index.assume %source_m [lt(%source_m, %m_size)] : index
        %narrow = vector.load %a_view[%bounded, %source_k] : view<[%m_size]x[%k_size]xf16> -> vector<4xf16>
        scf.yield %narrow : vector<4xf16>
      } else {
        scf.yield %zero_f16x4 : vector<4xf16>
      }""", GATHER)
    return HEADER.format(tile=tile, source=src_stem) + s


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-dir", type=Path, default=KERNELS)
    args = parser.parse_args()
    for target in SOURCES:
        out = args.output_dir / f"{target}.loom"
        out.write_text(derive(target))
        print(f"wrote {out}")


if __name__ == "__main__":
    main()
